### ISSUE TITLE
docker build error

### ISSUE THREAD

**Issue by adamsewell** [bludesign/FaxServer#11]
I'm looking for a solution to move a company to online faxes using Twilio and ran across this project, when I tried to install in docker it had an issue with mongodb and wouldn't start. Looking at the build details on docker, it's reporting this:

`Build failed: The command '/bin/sh -c vapor build --release --verbose' returned a non-zero code: 1`

https://hub.docker.com/r/bludesign/faxserver/builds/bfzbrecwsyhwnbp9nq5axrm/

Granted I'm not up to par on Docker so maybe it's something I'm doing.

**Comment by spreaderman** [comment]
Looks like a nice project but the installation instructions are quite vague for those with little docker experience.  I wonder if you can show what to expose using apache?

**Comment by chandlerhuff** [comment]
This has been fixed in the latest release run `docker-compose pull`
