### ISSUE TITLE
500 Error: There is no configured `DataDecoder` for content type: multipart/form-data; boundary=----

### ISSUE THREAD

**Issue by jeremiahgreer** [bludesign/FaxServer#7]
I am trying to add my Twilio account details...when I click Save, I am getting a 500 Error: There is no configured `DataDecoder` for content type: multipart/form-data; boundary=----WebKitFormBoundaryQe7gkLy6uvI9piiA.

**Comment by chandlerhuff** [comment]
Once the Docker [build](https://hub.docker.com/r/bludesign/faxserver/builds/) is finished you can pull the fixed version with `git pull` and `docker-compose pull`
